---
version: "2.0"

services:
  ironfish:
    image: ghcr.io/iron-fish/ironfish:latest
    command: ["ironfish", "start", "nodeName", "akash"]
    expose:
      - port: 9033
        as: 9033
        to:
          - global: true
      - port: 8020
        as: 8020
        to:
          - global: true
  ironfish-miner:
    image: ghcr.io/iron-fish/ironfish:latest
    command: ["ironfish", "miners:start", "--pool", "pool.ironfish.network", "--address", "d03f641e0008b9defe88562cd2a561dabec9f37ffd7a791757accc9d5e60e9005124c9d65755a97903e381", "--blockGraffiti", "akash"]
profiles:
  compute:
    ironfish:
      resources:
        cpu:
          units: 16.0
        memory:
          size: 16Gi
        storage:
          size: 128Gi
    ironfish-miner:
      resources:
        cpu:
          units: 16.0
        memory:
          size: 16Gi
        storage:
          size: 128Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        ironfish:
          denom: uakt
          amount: 100000
        ironfish-miner:
          denom: uakt
          amount: 100000

deployment:
  ironfish:
    akash:
      profile: ironfish
      count: 1
  ironfish-miner:
    akash:
      profile: ironfish-miner
      count: 1

