---
version: "2.0"

services:
  packetstream:
    image: packetstream/psclient:latest
    expose:
      - port: 80
        to:
          - global: true
    env:
      - CID=
profiles:
  compute:
    packetstream:
      resources:
        cpu:
          units: 1
          #Min 0.01 / Max 256 CPU's.
        memory:
          size: 256Mi
          #Min 256Mi / Max 512Gi.
        storage:
          size: 8Mi
          #packet-crypt is currently 20Mi in size
          #Min 32Mi / Max 32Ti
  placement:
    akash:
      pricing:
        packetstream:
          denom: uakt
          amount: 10000 #Keep high to show all bids
deployment:
  packetstream:
    akash:
      profile: packetstream
      count: 1

##Total deployment size cannot exceed 512vCPU / 512Gi / 32Ti
##You can reduce vCPU and increase count:1 to see more bids
##Example: cpu.units:2 and akash.count:10 will show more bids than 10 cpu.units and akash.count 2.
