---
version: "2.0"

services:
  miner-xmrig:
    image: cryptoandcoffee/akash-moneroocean:2
    expose:
      - port: 8080
        as: 80
        proto: tcp
        to:
          - global: true
    env:
      - WALLET=4AbG74FRUHYXBLkvqM1f7QH3UXGkhLetKdxS7U7BHkyfMF4nfx99GvN1REwYQHAeVLLy4Qa5gXXkfS4pSHHUWwdVFifDo5K
profiles:
  compute:
    miner-xmrig:
      resources:
        cpu:     # Max 10vCPU
          units: 4.0
        memory:  # Max 16Gi
          size:  1Gi
        storage: # Max 1Ti
          size:  1Gi
  placement:
    akash:
      pricing:
        miner-xmrig:
          denom: uakt
          amount: 1000 #Keep high to show all bids
deployment:
  miner-xmrig:
    akash:
      profile: miner-xmrig
      count: 1

##Total deployment size cannot exceed 20vCPU / 32Gi / 2Ti
##You can reduce vCPU and increase count:1 to see more bids
##Example: 2vCPU and count: 10 will show more bids than 10vcpu and count:2
