---
version: "2.0"

services:
  phoronix:
    image: cryptoandcoffee/akash-phoronix
    expose:
      - port: 80
        to:
          - global: true
profiles:
  compute:
    phoronix:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 8Gi #2Gi required
        storage:
          size: 1Gi
  placement:
    akash:
      pricing:
        phoronix:
          denom: uakt
          amount: 10000
deployment:
  phoronix:
    akash:
      profile: phoronix
      count: 1
