---
version: "2.0"

services:
  pkt-miner:
    image: cryptoandcoffee/akash-pkt-miner:6
    env:
      - WALLET_ADDR=
      - POOL1=http://pool.pkteer.com
      - POOL2=http://pool.pkt.world
      - POOL3=http://pool.pktpool.io
      - POOL4=https://stratum.zetahash.com
    expose:
      - port: 80
        to:
          - global: true
profiles:
  compute:
    pkt-miner:
      resources:
        cpu:
          units: 1
          #Min 0.01 / Max 256 CPU's.
        memory:
          size: 1Gi
          #Min 1Gi / Max 512Gi.
          #For best performance use at least 256Mi per cpu.unit requested above the 1Gi minimum required.
        storage:
          size: 1Gi
          #Min 16Gi / Max 32Ti
  placement:
    pkt-miner:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        pkt-miner:
          denom: uakt
          amount: 10000
deployment:
  pkt-miner:
    pkt-miner:
      profile: pkt-miner
      count: 1
##Total deployment size cannot exceed 512vCPU / 512Gi / 32Ti
##You can reduce vCPU and increase count:1 to see more bids
##Example: cpu.units:2 and akash.count:10 will show more bids than 10 cpu.units and akash.count 2.
