---
version: "2.0"

services:
  cross-platform-disk-test:
    image: cryptoandcoffee/akash-cross-platform-disk-test
    expose:
      - port: 80
        to:
          - global: true
profiles:
  compute:
    cross-platform-disk-test:
      resources:
        cpu:
          units: 8.0
        memory:
          size: 4Gi #2Gi required
        storage:
          size: 64Gi #64Gi min for the default test.
  placement:
    akash:
      pricing:
        cross-platform-disk-test:
          denom: uakt
          amount: 10000
deployment:
  cross-platform-disk-test:
    akash:
      profile: cross-platform-disk-test
      count: 1
